name: Deploy GitHub Page

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: demo
      url: ${{ steps.deploy_page.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vite GitHub Pages Deployer
        uses: skywarth/vite-github-pages-deployer@master
        id: deploy_page
